# Kurumlar ve Pozisyonlar - becayis.memurlar.net'ten alınmıştır

INSTITUTIONS = [
    "Adalet Bakanlığı",
    "Adli Tıp Kurumu Başkanlığı",
    "Afet ve Acil Durum Yönetimi Başkanlığı",
    "Aile, Çalışma ve Sosyal Hizmetler Bakanlığı",
    "Anayasa Mahkemesi",
    "Arsa Ofisi Genel Müdürlüğü",
    "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu",
    "Avrupa Birliği Başkanlığı",
    "Bankacılık Düzenleme ve Denetleme Kurumu",
    "Basın İlan Kurumu Genel Müdürlüğü",
    "Belediyeler",
    "Bilgi Teknolojileri ve İletişim Kurumu",
    "Boru Hatları ile Petrol Taşıma A.Ş.",
    "Ceza ve Tevkifevleri Genel Müdürlüğü",
    "Çay İşletmeleri Genel Müdürlüğü",
    "Çevre ve Şehircilik Bakanlığı",
    "Deniz Harp Okulu",
    "Deniz Kuvvetleri Komutanlığı",
    "Devlet Arşivleri Genel Müdürlüğü",
    "Devlet Hava Meydanları İşletmesi Genel Müdürlüğü",
    "Devlet Malzeme Ofisi Genel Müdürlüğü",
    "Devlet Meteoroloji İşleri Genel Müdürlüğü",
    "Devlet Opera ve Balesi Genel Müdürlüğü",
    "Devlet Su İşleri Genel Müdürlüğü",
    "Devlet Tiyatroları Genel Müdürlüğü",
    "Dışişleri Bakanlığı",
    "Diyanet İşleri Başkanlığı",
    "Elektrik Üretim A.Ş. Genel Müdürlüğü",
    "Emniyet Genel Müdürlüğü",
    "Enerji Piyasası Düzenleme Kurumu",
    "Enerji ve Tabii Kaynaklar Bakanlığı",
    "Et ve Süt Kurumu Genel Müdürlüğü",
    "Eti Maden İşletmesi Genel Müdürlüğü",
    "Gelir İdaresi Başkanlığı",
    "Gençlik ve Spor Bakanlığı",
    "Genelkurmay Başkanlığı",
    "Halk Bankası",
    "Hava Harp Okulu",
    "Hava Kuvvetleri Komutanlığı",
    "Hazine ve Maliye Bakanlığı",
    "Hudut ve Sahiller Sağlık Genel Müdürlüğü",
    "İçişleri Bakanlığı",
    "İl Özel İdareleri",
    "İller Bankası Genel Müdürlüğü",
    "Jandarma Genel Komutanlığı",
    "Kalkınma Bakanlığı",
    "Kara Kuvvetleri Komutanlığı",
    "Karayolları Genel Müdürlüğü",
    "Kıyı Emniyeti Genel Müdürlüğü",
    "Kredi Yurtlar Kurumu",
    "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı",
    "Kültür ve Turizm Bakanlığı",
    "Maden Tetkik ve Arama Genel Müdürlüğü",
    "Maden ve Petrol İşleri Genel Müdürlüğü",
    "Makine ve Kimya Endüstrisi Kurumu",
    "Merkez Bankası",
    "Milli Eğitim Bakanlığı",
    "Milli Piyango İdaresi Genel Müdürlüğü",
    "Milli Savunma Bakanlığı",
    "Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü",
    "Orman Genel Müdürlüğü",
    "PTT",
    "Sağlık Bakanlığı",
    "Sahil Güvenlik Komutanlığı",
    "Sanayi ve Teknoloji Bakanlığı",
    "Savunma Sanayi Müsteşarlığı",
    "Sivil Havacılık Genel Müdürlüğü",
    "Sosyal Güvenlik Kurumu",
    "Sosyal Yardımlaşma ve Dayanışma Genel Müdürlüğü",
    "Spor Genel Müdürlüğü",
    "Tapu ve Kadastro Genel Müdürlüğü",
    "Tarım İşletmeleri Genel Müdürlüğü",
    "Tarım Kredi Koop. Merkez Birliği",
    "Tarım ve Kırsal Kalkınmayı Destekleme Kurumu",
    "Tarım ve Orman Bakanlığı",
    "Tarımsal Üretim ve Geliştirme Genel Müdürlüğü",
    "TCDD Taşımacılık A.Ş.",
    "Ticaret Bakanlığı (Gümrük)",
    "Toprak Mahsülleri Ofisi Genel Müdürlüğü",
    "Türk İşbirliği ve Kalkınma İdaresi Başkanlığı",
    "Türk Patent Enstitüsü",
    "Türk Standartları Enstitüsü",
    "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    "Türkiye Cumhuriyeti Devlet Demiryolları",
    "Türkiye Demiryolu Makineleri Sanayi A.Ş",
    "Türkiye Elektrik Dağıtım A.Ş.",
    "Türkiye Elektrik İletim A.Ş.",
    "Türkiye Elektromekanik Sanayii A.Ş. Genel Müdürlüğü",
    "Türkiye İstatistik Kurumu",
    "Türkiye İş Kurumu Genel Müdürlüğü",
    "Türkiye Kömür İşletmeleri Genel Müdürlüğü",
    "Türkiye Lokomotif ve Motor Sanayi AŞ",
    "Türkiye Petrolleri Anonim Ortaklığı",
    "Türkiye Şeker Fabrikaları A.Ş.",
    "Türkiye Taş Kömürü Kurumu",
    "Türkiye Vagon Sanayi A.Ş.",
    "Türkiye Yazma Eserler Kurumu Başkanlığı",
    "Türksat Uydu Haberleşme ve Kablo TV İşletme A.Ş",
    "Ulaştırma ve Altyapı Bakanlığı",
    "Ulusal Bor Araştırma Enstitüsü",
    "Üniversiteler",
    "Vakıflar Genel Müdürlüğü",
    "Yargıtay",
    "Yüksek Seçim Kurulu Başkanlığı",
    "Ziraat Bankası Genel Müdürlüğü"
]

POSITIONS = [
    "Acil Tıp Teknikeri",
    "Acil Tıp Teknisyeni",
    "Anbar Memuru",
    "Anestezi Teknikeri",
    "Anestezi Teknisyeni",
    "Antrenör",
    "Araştırmacı",
    "Arkeolog",
    "Aşçı",
    "Avukat",
    "Ayniyat Memuru",
    "Bahçıvan",
    "Bakıcı Anne",
    "Başhemşire",
    "Başmühendis",
    "Bekçi",
    "Berber",
    "Bilgisayar İşletmeni",
    "Biyolog",
    "Büro Personeli",
    "Büro Personeli (4/B)",
    "Cezaevi Katibi",
    "Cezaevi Tabibi",
    "Çevre Sağlık Teknisyeni",
    "Çocuk Bakıcısı",
    "Çocuk Eğitimcisi",
    "Çocuk Gelişimcisi",
    "Çözümleyici",
    "Dağıtıcı",
    "Daire Başkanı",
    "Daktilograf",
    "Dava Takip Memuru",
    "Dekoratör",
    "Desinatör",
    "Diş Hekimi",
    "Diş Protez Teknikeri",
    "Diş Protez Teknisyeni",
    "Diş Tabibi",
    "Diyaliz Teknikeri",
    "Diyetisyen",
    "Ebe",
    "Eczacı",
    "Eğitim Uzmanı",
    "Ekonomist",
    "Emanet Memuru",
    "Enformasyon Memuru",
    "Ev Ekonomisti",
    "Fen Memuru",
    "Fizikçi",
    "Fizyoterapist",
    "Fotoğrafçı",
    "Garson",
    "Gassal",
    "Gemi Adamı",
    "Gemi Sicil Memuru",
    "Gemici",
    "Gişe Memuru",
    "Grafiker",
    "Haberleşme Memuru",
    "Hademe",
    "Harita Çizimcisi",
    "Harita Mutemedi",
    "Hastabakıcı",
    "Hava Trafik Kontrolörü",
    "Hayvan Bakıcısı",
    "Hazine Avukatı",
    "Hemşire",
    "Hemşire (4/B)",
    "Hemşire Yardımcısı",
    "Heykeltıraş",
    "Hizmetli",
    "Hostes",
    "İcra Memuru",
    "İcra Kâtibi",
    "İdare Memuru",
    "İdari Büro Görevlisi",
    "İmam-Hatip",
    "İnfaz Koruma Başmemuru",
    "İnfaz Koruma Memuru",
    "İstatistikçi",
    "İş Makinası Sürücüsü",
    "İş ve Meslek Danışmanı",
    "İtfaiyeci",
    "Jeofizikçi",
    "Jeolog",
    "Jeoloji Mühendisi",
    "Jeomorfolog",
    "Kadastro Teknisyeni",
    "Kaloriferci",
    "Kameraman",
    "Kaptan",
    "Kartograf",
    "Kılavuz Kaptan",
    "Kimyager",
    "Kitap Pataloğu",
    "Kolcu",
    "Komiser",
    "Kontrol Memuru",
    "Kontrol Mühendisi",
    "Kontrolör",
    "Koruma ve Güvenlik Görevlisi",
    "Koruma ve Güvenlik Amiri",
    "Koruma ve Güvenlik Şefi",
    "Kuran Kursu Öğreticisi",
    "Kütüphaneci",
    "Laborant",
    "Laborant Yardımcısı",
    "Laboratuvar Teknikeri",
    "Laboratuvar Teknisyeni",
    "Makinist",
    "Makinist Yardımcısı",
    "Makyajcı",
    "Matbaacı",
    "Matematikçi",
    "Memur",
    "Mimar",
    "Muayene Memuru",
    "Muhafaza Memuru",
    "Muhasebeci",
    "Mutemet",
    "Mübaşir",
    "Müezzin-Kayyım",
    "Mühendis",
    "Mütercim",
    "Odolog",
    "Odyometri Teknikeri",
    "Operatör",
    "Orman Muhafaza Memuru",
    "Ortopedi Teknisyeni",
    "Öğretmen",
    "Ölçü ve Ayar Memuru",
    "Pataloji Teknikeri",
    "Pazarlamacı",
    "Pedagog",
    "Pilot",
    "Polis Memuru",
    "Postacı",
    "Pratisyen Tabip",
    "Programcı",
    "Programcı Yardımcısı",
    "Protez/Ortez Teknikeri",
    "Psikolog",
    "Puantör",
    "Radyoloji Teknikeri",
    "Radyoloji Teknisyeni",
    "Radyoterapi Teknikeri",
    "Radyoterapist",
    "Raportör",
    "Rasatçı",
    "Redaktör",
    "Rehber",
    "Repartitör",
    "Ressam",
    "Restoratör",
    "Revizör",
    "Röntgen Teknisyeni",
    "Sağlık Fizikçisi",
    "Sağlık Memuru",
    "Sağlık Teknikeri",
    "Sağlık Teknisyeni",
    "Santral Memuru",
    "Satınalma Memuru",
    "Satış Memuru",
    "Sayıcı",
    "Sayman",
    "Sekreter",
    "Ses Kayıtçısı",
    "Sicil Katibi",
    "Sicil Memuru",
    "Sistem Programcısı",
    "Sivil Memur",
    "Sivil Savunma Memuru",
    "Sosyal Çalışmacı",
    "Sosyolog",
    "Spiker",
    "Sürveyan",
    "Şef",
    "Şef Yardımcısı",
    "Şehir Plancısı",
    "Şoför",
    "Tabip",
    "Tahsildar",
    "Tapu Arşiv Memuru",
    "Tapu Tetkik Memuru",
    "Tebligat Memuru",
    "Teknik Amir",
    "Teknik Ressam",
    "Teknik Şef",
    "Teknik Uzman",
    "Tekniker",
    "Tekniker (4/B)",
    "Teknisyen",
    "Teknisyen (4/B)",
    "Teknisyen Yardımcısı",
    "Tercüman",
    "Terzi",
    "Tıbbi Sekreter",
    "Tıbbi Sekreter (4/B)",
    "Tıbbi Teknolog",
    "Toplum Sağlığı Teknisyeni",
    "Topoğraf",
    "Tren Teşkil Memuru",
    "Uçak Kontrol Makinisti",
    "Uçak Telsizcisi",
    "Usta Öğretici",
    "Ustabaşı",
    "Uzman",
    "Uzman Tabip",
    "Uzman Yardımcısı",
    "Vagon Teknisyeni",
    "Vaiz",
    "Veteriner Hekim",
    "Veteriner Sağlık Teknikeri",
    "Veteriner Sağlık Teknisyeni",
    "Veznedar",
    "VHKİ",
    "Yoklama Memuru",
    "Yurt Yönetim Memuru",
    "Zabıt Katibi",
    "Zabıt Katibi (4/B)",
    "Zabıta Memuru"
]

# SSS - becayis.memurlar.net'ten alınmıştır
FAQ_DATA = [
    {
        "question": "Becayiş nedir?",
        "answer": "Becayiş, tanım olarak karşılıklı olarak yer değiştirmektir. 657 sayılı Kanunun 73'üncü maddesinde tanımlanmıştır: 'Aynı kurumun başka başka yerlerde bulunan aynı sınıftaki memurları, karşılıklı olarak yer değiştirme suretiyle atanmalarını isteyebilirler.' Bu tanıma göre; becayiş aynı kurum personeli arasında yapılır, sınıf ve ünvan aynı olmalıdır ve atamaya yetkili amirce uygun bulunması gerekmektedir."
    },
    {
        "question": "Becayişin dönemi var mıdır?",
        "answer": "657 sayılı Kanunda becayiş için bir dönem öngörülmemiştir. Ancak öğretmenlerin eğitim ve öğretimin bütünlüğü çerçevesinde ara tatil veya okul bitiminde başvurmaları daha uygun olacaktır."
    },
    {
        "question": "Becayişin kabul edilmeme ihtimali var mıdır?",
        "answer": "657 sayılı Kanun, her ne kadar becayiş için atamaya yetkili amirin onayını zorunlu görmüşse de, onay verilmemesi için hiçbir sebep bulunmamaktadır. İdarenin yaptığı ve yapacağı tüm işlemlerin kamu yararına uygun olması gerekmektedir. Becayişte kamu yararı açısından, olumsuz cevap verilmesini gerektirecek hiçbir neden bulunmamaktadır. Bu nedenle uygun becayiş talebine izin verilmemesi halinde açılacak bir dava kazanılır."
    },
    {
        "question": "Becayiş ve zorunlu hizmet ilişkisi nedir?",
        "answer": "Öğretmenler ve sağlık personeli zorunlu hizmete tabidir. Bu nedenle zorunlu hizmet gören personelin becayiş isteyeceği ilin de zorunlu hizmet bölgesi kapsamında olması gerekmektedir."
    },
    {
        "question": "Kimler kendi aralarında becayiş yapabilir?",
        "answer": "Becayiş aynı kurum personeli arasında yapılır. Yani farklı kurumların personeli (örneğin Sağlık Bakanlığı personeli ile Maliye Bakanlığı personeli) karşılıklı olarak yer değiştiremez. Ayrıca sınıf ve ünvan aynı olmalıdır. Örneğin bilgisayar mühendisleri kendi aralarında, hemşireler kendi aralarında becayiş yapabilirler."
    },
    {
        "question": "Becayiş başvurusu nasıl yapılır?",
        "answer": "Becayiş yapmak isteyen personelin bir dilekçe ile bölge, il veya ilçe müdürlükleri aracılığı ile Bakanlığa başvurması gerekmektedir. Bakanlığın da bu talebi uygun görmesi halinde becayiş gerçekleşir."
    },
    {
        "question": "İletişim bilgilerim ne zaman paylaşılır?",
        "answer": "İletişim bilgileriniz (telefon, e-posta) gizlidir ve sadece gönderdiğiniz veya aldığınız bir talebi kabul ettiğinizde karşı tarafla paylaşılır. Talep kabul edilmeden bilgileriniz kimseyle paylaşılmaz."
    },
    {
        "question": "Platformda kaç hesap açabilirim?",
        "answer": "Her kişi yalnızca BİR hesap oluşturabilir. Birden fazla hesap oluşturma durumunda hesaplarınız engellenebilir."
    }
]

# İller listesi
PROVINCES = [
    "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya",
    "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik",
    "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum",
    "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir",
    "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Iğdır", "Isparta", "İstanbul",
    "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kırıkkale",
    "Kırklareli", "Kırşehir", "Kilis", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa",
    "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye",
    "Rize", "Sakarya", "Samsun", "Siirt", "Sinop", "Sivas", "Şanlıurfa", "Şırnak",
    "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak"
]


# İlçeler - Türkiye'nin 81 ili için
DISTRICTS = {
    "Adana": ["Aladağ", "Ceyhan", "Çukurova", "Feke", "İmamoğlu", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir"],
    "Adıyaman": ["Adıyaman Merkez", "Besni", "Çelikhan", "Gerger", "Gölbaşı", "Kahta", "Samsat", "Sincik", "Tut"],
    "Afyonkarahisar": ["Afyonkarahisar Merkez", "Başmakçı", "Bayat", "Bolvadin", "Çay", "Çobanlar", "Dazkırı", "Dinar", "Emirdağ", "Evciler", "Hocalar", "İhsaniye", "İscehisar", "Kızılören", "Sandıklı", "Sinanpaşa", "Sultandağı", "Şuhut"],
    "Ağrı": ["Ağrı Merkez", "Diyadin", "Doğubayazıt", "Eleşkirt", "Hamur", "Patnos", "Taşlıçay", "Tutak"],
    "Aksaray": ["Aksaray Merkez", "Ağaçören", "Eskil", "Gülağaç", "Güzelyurt", "Ortaköy", "Sarıyahşi"],
    "Amasya": ["Amasya Merkez", "Göynücek", "Gümüşhacıköy", "Hamamözü", "Merzifon", "Suluova", "Taşova"],
    "Ankara": ["Akyurt", "Altındağ", "Ayaş", "Balâ", "Beypazarı", "Çamlıdere", "Çankaya", "Çubuk", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kahramankazan", "Kalecik", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Şereflikoçhisar", "Yenimahalle"],
    "Antalya": ["Akseki", "Aksu", "Alanya", "Demre", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "İbradı", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik"],
    "Ardahan": ["Ardahan Merkez", "Çıldır", "Damal", "Göle", "Hanak", "Posof"],
    "Artvin": ["Ardanuç", "Arhavi", "Artvin Merkez", "Borçka", "Hopa", "Kemalpaşa", "Murgul", "Şavşat", "Yusufeli"],
    "Aydın": ["Bozdoğan", "Buharkent", "Çine", "Didim", "Efeler", "Germencik", "İncirliova", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Kuşadası", "Kuyucak", "Nazilli", "Söke", "Sultanhisar", "Yenipazar"],
    "Balıkesir": ["Altıeylül", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "İvrindi", "Karesi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Sındırgı", "Susurluk"],
    "Bartın": ["Amasra", "Bartın Merkez", "Kurucaşile", "Ulus"],
    "Batman": ["Batman Merkez", "Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Sason"],
    "Bayburt": ["Aydıntepe", "Bayburt Merkez", "Demirözü"],
    "Bilecik": ["Bilecik Merkez", "Bozüyük", "Gölpazarı", "İnhisar", "Osmaneli", "Pazaryeri", "Söğüt", "Yenipazar"],
    "Bingöl": ["Adaklı", "Bingöl Merkez", "Genç", "Karlıova", "Kiğı", "Solhan", "Yayladere", "Yedisu"],
    "Bitlis": ["Adilcevaz", "Ahlat", "Bitlis Merkez", "Güroymak", "Hizan", "Mutki", "Tatvan"],
    "Bolu": ["Bolu Merkez", "Dörtdivan", "Gerede", "Göynük", "Kıbrıscık", "Mengen", "Mudurnu", "Seben", "Yeniçağa"],
    "Burdur": ["Ağlasun", "Altınyayla", "Bucak", "Burdur Merkez", "Çavdır", "Çeltikçi", "Gölhisar", "Karamanlı", "Kemer", "Tefenni", "Yeşilova"],
    "Bursa": ["Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "İnegöl", "İznik", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım"],
    "Çanakkale": ["Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Çan", "Çanakkale Merkez", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Yenice"],
    "Çankırı": ["Atkaracalar", "Bayramören", "Çankırı Merkez", "Çerkeş", "Eldivan", "Ilgaz", "Kızılırmak", "Korgun", "Kurşunlu", "Orta", "Şabanözü", "Yapraklı"],
    "Çorum": ["Alaca", "Bayat", "Boğazkale", "Çorum Merkez", "Dodurga", "İskilip", "Kargı", "Laçin", "Mecitözü", "Oğuzlar", "Ortaköy", "Osmancık", "Sungurlu", "Uğurludağ"],
    "Denizli": ["Acıpayam", "Babadağ", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Buldan", "Çal", "Çameli", "Çardak", "Çivril", "Güney", "Honaz", "Kale", "Merkezefendi", "Pamukkale", "Sarayköy", "Serinhisar", "Tavas"],
    "Diyarbakır": ["Bağlar", "Bismil", "Çermik", "Çınar", "Çüngüş", "Dicle", "Eğil", "Ergani", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir"],
    "Düzce": ["Akçakoca", "Cumayeri", "Çilimli", "Düzce Merkez", "Gölyaka", "Gümüşova", "Kaynaşlı", "Yığılca"],
    "Edirne": ["Edirne Merkez", "Enez", "Havsa", "İpsala", "Keşan", "Lalapaşa", "Meriç", "Süloğlu", "Uzunköprü"],
    "Elazığ": ["Ağın", "Alacakaya", "Arıcak", "Baskil", "Elazığ Merkez", "Karakoçan", "Keban", "Kovancılar", "Maden", "Palu", "Sivrice"],
    "Erzincan": ["Çayırlı", "Erzincan Merkez", "İliç", "Kemah", "Kemaliye", "Otlukbeli", "Refahiye", "Tercan", "Üzümlü"],
    "Erzurum": ["Aşkale", "Aziziye", "Çat", "Hınıs", "Horasan", "İspir", "Karaçoban", "Karayazı", "Köprüköy", "Narman", "Oltu", "Olur", "Palandöken", "Pasinler", "Pazaryolu", "Şenkaya", "Tekman", "Tortum", "Uzundere", "Yakutiye"],
    "Eskişehir": ["Alpu", "Beylikova", "Çifteler", "Günyüzü", "Han", "İnönü", "Mahmudiye", "Mihalgazi", "Mihalıççık", "Odunpazarı", "Sarıcakaya", "Seyitgazi", "Sivrihisar", "Tepebaşı"],
    "Gaziantep": ["Araban", "İslahiye", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Şahinbey", "Şehitkamil", "Yavuzeli"],
    "Giresun": ["Alucra", "Bulancak", "Çamoluk", "Çanakçı", "Dereli", "Doğankent", "Espiye", "Eynesil", "Giresun Merkez", "Görele", "Güce", "Keşap", "Piraziz", "Şebinkarahisar", "Tirebolu", "Yağlıdere"],
    "Gümüşhane": ["Gümüşhane Merkez", "Kelkit", "Köse", "Kürtün", "Şiran", "Torul"],
    "Hakkari": ["Çukurca", "Hakkari Merkez", "Şemdinli", "Yüksekova"],
    "Hatay": ["Altınözü", "Antakya", "Arsuz", "Belen", "Defne", "Dörtyol", "Erzin", "Hassa", "İskenderun", "Kırıkhan", "Kumlu", "Payas", "Reyhanlı", "Samandağ", "Yayladağı"],
    "Iğdır": ["Aralık", "Iğdır Merkez", "Karakoyunlu", "Tuzluca"],
    "Isparta": ["Aksu", "Atabey", "Eğirdir", "Gelendost", "Gönen", "Isparta Merkez", "Keçiborlu", "Senirkent", "Sütçüler", "Şarkikaraağaç", "Uluborlu", "Yalvaç", "Yenişarbademli"],
    "İstanbul": ["Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüpsultan", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu"],
    "İzmir": ["Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla"],
    "Kahramanmaraş": ["Afşin", "Andırın", "Çağlayancerit", "Dulkadiroğlu", "Ekinözü", "Elbistan", "Göksun", "Nurhak", "Onikişubat", "Pazarcık", "Türkoğlu"],
    "Karabük": ["Eflani", "Eskipazar", "Karabük Merkez", "Ovacık", "Safranbolu", "Yenice"],
    "Karaman": ["Ayrancı", "Başyayla", "Ermenek", "Karaman Merkez", "Kazımkarabekir", "Sarıveliler"],
    "Kars": ["Akyaka", "Arpaçay", "Digor", "Kağızman", "Kars Merkez", "Sarıkamış", "Selim", "Susuz"],
    "Kastamonu": ["Abana", "Ağlı", "Araç", "Azdavay", "Bozkurt", "Cide", "Çatalzeytin", "Daday", "Devrekani", "Doğanyurt", "Hanönü", "İhsangazi", "İnebolu", "Kastamonu Merkez", "Küre", "Pınarbaşı", "Seydiler", "Şenpazar", "Taşköprü", "Tosya"],
    "Kayseri": ["Akkışla", "Bünyan", "Develi", "Felahiye", "Hacılar", "İncesu", "Kocasinan", "Melikgazi", "Özvatan", "Pınarbaşı", "Sarıoğlan", "Sarız", "Talas", "Tomarza", "Yahyalı", "Yeşilhisar"],
    "Kırıkkale": ["Bahşılı", "Balışeyh", "Çelebi", "Delice", "Karakeçili", "Keskin", "Kırıkkale Merkez", "Sulakyurt", "Yahşihan"],
    "Kırklareli": ["Babaeski", "Demirköy", "Kırklareli Merkez", "Kofçaz", "Lüleburgaz", "Pehlivanköy", "Pınarhisar", "Vize"],
    "Kırşehir": ["Akçakent", "Akpınar", "Boztepe", "Çiçekdağı", "Kaman", "Kırşehir Merkez", "Mucur"],
    "Kilis": ["Elbeyli", "Kilis Merkez", "Musabeyli", "Polateli"],
    "Kocaeli": ["Başiskele", "Çayırova", "Darıca", "Derince", "Dilovası", "Gebze", "Gölcük", "İzmit", "Kandıra", "Karamürsel", "Kartepe", "Körfez"],
    "Konya": ["Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Çeltik", "Çumra", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadim", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak"],
    "Kütahya": ["Altıntaş", "Aslanapa", "Çavdarhisar", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Hisarcık", "Kütahya Merkez", "Pazarlar", "Simav", "Şaphane", "Tavşanlı"],
    "Malatya": ["Akçadağ", "Arapgir", "Arguvan", "Battalgazi", "Darende", "Doğanşehir", "Doğanyol", "Hekimhan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Yeşilyurt"],
    "Manisa": ["Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kırkağaç", "Köprübaşı", "Kula", "Salihli", "Sarıgöl", "Saruhanlı", "Selendi", "Soma", "Şehzadeler", "Turgutlu", "Yunusemre"],
    "Mardin": ["Artuklu", "Dargeçit", "Derik", "Kızıltepe", "Mazıdağı", "Midyat", "Nusaybin", "Ömerli", "Savur", "Yeşilli"],
    "Mersin": ["Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir"],
    "Muğla": ["Bodrum", "Dalaman", "Datça", "Fethiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Menteşe", "Milas", "Ortaca", "Seydikemer", "Ula", "Yatağan"],
    "Muş": ["Bulanık", "Hasköy", "Korkut", "Malazgirt", "Muş Merkez", "Varto"],
    "Nevşehir": ["Acıgöl", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Nevşehir Merkez", "Ürgüp"],
    "Niğde": ["Altunhisar", "Bor", "Çamardı", "Çiftlik", "Niğde Merkez", "Ulukışla"],
    "Ordu": ["Akkuş", "Altınordu", "Aybastı", "Çamaş", "Çatalpınar", "Çaybaşı", "Fatsa", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Perşembe", "Ulubey", "Ünye"],
    "Osmaniye": ["Bahçe", "Düziçi", "Hasanbeyli", "Kadirli", "Osmaniye Merkez", "Sumbas", "Toprakkale"],
    "Rize": ["Ardeşen", "Çamlıhemşin", "Çayeli", "Derepazarı", "Fındıklı", "Güneysu", "Hemşin", "İkizdere", "İyidere", "Kalkandere", "Pazar", "Rize Merkez"],
    "Sakarya": ["Adapazarı", "Akyazı", "Arifiye", "Erenler", "Ferizli", "Geyve", "Hendek", "Karapürçek", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Sapanca", "Serdivan", "Söğütlü", "Taraklı"],
    "Samsun": ["Alaçam", "Asarcık", "Atakum", "Ayvacık", "Bafra", "Canik", "Çarşamba", "Havza", "İlkadım", "Kavak", "Ladik", "Ondokuzmayıs", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü", "Yakakent"],
    "Siirt": ["Baykan", "Eruh", "Kurtalan", "Pervari", "Siirt Merkez", "Şirvan", "Tillo"],
    "Sinop": ["Ayancık", "Boyabat", "Dikmen", "Durağan", "Erfelek", "Gerze", "Saraydüzü", "Sinop Merkez", "Türkeli"],
    "Sivas": ["Akıncılar", "Altınyayla", "Divriği", "Doğanşar", "Gemerek", "Gölova", "Hafik", "İmranlı", "Kangal", "Koyulhisar", "Sivas Merkez", "Suşehri", "Şarkışla", "Ulaş", "Yıldızeli", "Zara"],
    "Şanlıurfa": ["Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Eyyübiye", "Halfeti", "Haliliye", "Harran", "Hilvan", "Karaköprü", "Siverek", "Suruç", "Viranşehir"],
    "Şırnak": ["Beytüşşebap", "Cizre", "Güçlükonak", "İdil", "Silopi", "Şırnak Merkez", "Uludere"],
    "Tekirdağ": ["Çerkezköy", "Çorlu", "Ergene", "Hayrabolu", "Kapaklı", "Malkara", "Marmaraereğlisi", "Muratlı", "Saray", "Süleymanpaşa", "Şarköy"],
    "Tokat": ["Almus", "Artova", "Başçiftlik", "Erbaa", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Tokat Merkez", "Turhal", "Yeşilyurt", "Zile"],
    "Trabzon": ["Akçaabat", "Araklı", "Arsin", "Beşikdüzü", "Çarşıbaşı", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Maçka", "Of", "Ortahisar", "Sürmene", "Şalpazarı", "Tonya", "Vakfıkebir", "Yomra"],
    "Tunceli": ["Çemişgezek", "Hozat", "Mazgirt", "Nazımiye", "Ovacık", "Pertek", "Pülümür", "Tunceli Merkez"],
    "Uşak": ["Banaz", "Eşme", "Karahallı", "Sivaslı", "Ulubey", "Uşak Merkez"],
    "Van": ["Bahçesaray", "Başkale", "Çaldıran", "Çatak", "Edremit", "Erciş", "Gevaş", "Gürpınar", "İpekyolu", "Muradiye", "Özalp", "Saray", "Tuşba"],
    "Yalova": ["Altınova", "Armutlu", "Çınarcık", "Çiftlikköy", "Termal", "Yalova Merkez"],
    "Yozgat": ["Akdağmadeni", "Aydıncık", "Boğazlıyan", "Çandır", "Çayıralan", "Çekerek", "Kadışehri", "Saraykent", "Sarıkaya", "Sorgun", "Şefaatli", "Yenifakılı", "Yerköy", "Yozgat Merkez"],
    "Zonguldak": ["Alaplı", "Çaycuma", "Devrek", "Ereğli", "Gökçebey", "Kilimli", "Kozlu", "Zonguldak Merkez"]
}
